model:
  arch: mini_gpt4_llama_v2
  model_type: minigpt4_video
  llama_model: "meta-llama/Llama-2-7b-chat-hf"

  max_txt_len: 160
  max_context_len: 512
  end_sym: "</s>"
  prompt_path: "train_configs/alignment.txt"
  prompt_template: '[INST] {} [/INST] '
  ckpt: "checkpoints/pretrained_minigpt4_llama2_7b.pth"
  architectures: [
    "MiniGPT4_Video"
  ]
  device: "cuda"
  drop_path_rate: 0 
  img_size: 224
  
  #model_type: "minigpt4_video"
  num_query_token: 32
  prompt: ""
  torch_dtype: "float32"
  vit_precision: "fp16"
  vit_model: "eva_clip_g"
  lora_target_modules : ["q_proj","v_proj"]
  lora_dropout: 0.05
  remove_template: false
  token_pooling: True
  low_resource: False
  use_grad_checkpoint: True       # 显存优化
  use_grad_checkpoint_llm: True   # 【关键修复】漏掉的就是它！
  lora_r: 64
  lora_alpha: 16
  length: 50
  chat_template: True

datasets:
  laion:
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 5
  iters_per_epoch: 100
  num_workers: 4
  warmup_steps: 50

  seed: 42
  output_dir: "output/minigpt4_stage2_finetune"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: minigpt4_finetune1
